"""Remove role field

Revision ID: 3b386f8c16aa
Revises: f8ae84f68863
Create Date: 2021-11-18 19:10:17.825591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b386f8c16aa'
down_revision = 'f8ae84f68863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
