"""Add difficuly of the session

Revision ID: 5fb8a7c20d00
Revises: b56e2d396ba1
Create Date: 2021-11-18 17:15:44.114176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb8a7c20d00'
down_revision = 'b56e2d396ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('difficulty', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'difficulty')
    # ### end Alembic commands ###
