"""Add start_at field to the session

Revision ID: b56e2d396ba1
Revises: 099c4ccdcf60
Create Date: 2021-11-18 15:09:57.426312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56e2d396ba1'
down_revision = '099c4ccdcf60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('started_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'started_at')
    # ### end Alembic commands ###
