"""Add number to the user table

Revision ID: c26ecf3f726e
Revises: 5fb8a7c20d00
Create Date: 2021-11-18 18:35:55.901624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26ecf3f726e'
down_revision = '5fb8a7c20d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'number')
    # ### end Alembic commands ###
